#!/bin/sh
# Update der Sperrlisten fuer squidGuard auf die Listen von repo.cephalix.eu
#
# (C) 2022 Peter Varkoly <pvarkoly@cephalix.eu>
# Thomas Litsch <tl@extis.de>, 24.04.2008
#

# Neue Listen runterladen

cd /var/lib/squidGuard/db
rm -f cranix-blacklists.txz

/usr/bin/wget -O cranix-blacklists.txz -o /var/log/cranix-blacklists-updates.log http://repo.cephalix.eu/cranix-blacklists.txz
if [ ! -s cranix-blacklists.txz ]; then
	echo "Cranix list could not been downlowded"
	exit 1
fi
/bin/tar xzf cranix-blacklists.txz

# Erzeugen der Datenbankdateien aus den domain und url Dateien.
# Muss nach jedem Einspielen der Listen gemacht werden, da diese
# immer komplett neu geladen werden und nicht als diff vorliegen.
date >> /var/log/cranix-blacklists-updates.log
/usr/bin/systemctl stop squid >> /var/log/cranix-blacklists-updates.log
/usr/sbin/squidGuard -d -c /etc/squid/squidguard.conf -C all >> /var/log/cranix-blacklists-updates.log 2>&1
/bin/chown -R squid.nogroup /var/lib/squidGuard/db/BL
/bin/chown -R squid.nogroup /var/log/squidGuard/
/usr/bin/systemctl start squid >> /var/log/cranix-blacklists-updates.log

exit 0

# Die muesste/koennte noch eingebunden werden...
#/usr/bin/wget ftp://ftp.univ-tlse1.fr/pub/reseau/cache/squidguard_contrib/blacklists.tar.gz
