INSERT INTO Translations VALUES(NULL,'NL','news','Nieuws');
INSERT INTO Translations VALUES(NULL,'NL','shopping','Shopping');
INSERT INTO Translations VALUES(NULL,'NL','warez','Warez');
INSERT INTO Translations VALUES(NULL,'NL','aggressive','Aggressief ');
INSERT INTO Translations VALUES(NULL,'NL','spyware','Spyware');
INSERT INTO Translations VALUES(NULL,'NL','webradio','Internet radios');
INSERT INTO Translations VALUES(NULL,'NL','gamble','Gokken/Casinospelen');
INSERT INTO Translations VALUES(NULL,'NL','automobile-bikes','Automobil/Motorfiets ');
INSERT INTO Translations VALUES(NULL,'NL','music','Muziek');
INSERT INTO Translations VALUES(NULL,'NL','hacking','Hacking');
INSERT INTO Translations VALUES(NULL,'NL','adv','Reclame');
INSERT INTO Translations VALUES(NULL,'NL','dating','Dating');
INSERT INTO Translations VALUES(NULL,'NL','porn','18+');
INSERT INTO Translations VALUES(NULL,'NL','tracker','Tracker');
INSERT INTO Translations VALUES(NULL,'NL','drugs','Verdovende middelen');
INSERT INTO Translations VALUES(NULL,'NL','webmail','Webmail');
INSERT INTO Translations VALUES(NULL,'NL','isp','Internet Service Provider');
INSERT INTO Translations VALUES(NULL,'NL','automobile-cars','Automobil/Auto');
INSERT INTO Translations VALUES(NULL,'NL','forum','Forum');
INSERT INTO Translations VALUES(NULL,'NL','models','Models');
INSERT INTO Translations VALUES(NULL,'NL','redirector','Proxy');
INSERT INTO Translations VALUES(NULL,'IT','costtraps','Servizi Gratuiti Fittizzi');
INSERT INTO Translations VALUES(NULL,'IT','sex-lingerie','Intimo');
INSERT INTO Translations VALUES(NULL,'IT','weapons','Armi');
INSERT INTO Translations VALUES(NULL,'IT','updatesites','Siti di Aggiornamento');
INSERT INTO Translations VALUES(NULL,'IT','news','Notizie');
INSERT INTO Translations VALUES(NULL,'IT','religion','Religione');
INSERT INTO Translations VALUES(NULL,'IT','shopping','Shopping');
INSERT INTO Translations VALUES(NULL,'IT','violence','Violenza');
INSERT INTO Translations VALUES(NULL,'IT','hobby-pets','Hobby/Animali');
INSERT INTO Translations VALUES(NULL,'IT','webtv','Internet TV');
INSERT INTO Translations VALUES(NULL,'IT','automobile-boats','Automobile/Barche');
INSERT INTO Translations VALUES(NULL,'IT','recreation-travel','Ricreativi/Viaggi');
INSERT INTO Translations VALUES(NULL,'IT','warez','Warez');
INSERT INTO Translations VALUES(NULL,'IT','hospitals','Ospedali');
INSERT INTO Translations VALUES(NULL,'IT','aggressive','Aggressività');
INSERT INTO Translations VALUES(NULL,'IT','downloads','Downloads');
INSERT INTO Translations VALUES(NULL,'IT','homestyle','Arredamenti Casa');
INSERT INTO Translations VALUES(NULL,'IT','spyware','Spyware');
INSERT INTO Translations VALUES(NULL,'IT','webradio','Internet Radio');
INSERT INTO Translations VALUES(NULL,'IT','government','Governo');
INSERT INTO Translations VALUES(NULL,'IT','politics','Politica');
INSERT INTO Translations VALUES(NULL,'IT','hobby-cooking','Hobby/Cucina');
INSERT INTO Translations VALUES(NULL,'IT','podcasts','Podcasts');
INSERT INTO Translations VALUES(NULL,'IT','gamble','Gioco d\'azzardo');
INSERT INTO Translations VALUES(NULL,'IT','automobile-bikes','Automobile/Biciclette');
INSERT INTO Translations VALUES(NULL,'IT','jobsearch','Ricerca Lavoro');
INSERT INTO Translations VALUES(NULL,'IT','military','Militari');
INSERT INTO Translations VALUES(NULL,'IT','music','Musica');
INSERT INTO Translations VALUES(NULL,'IT','science-astronomy','Scienza/Astronomia');
INSERT INTO Translations VALUES(NULL,'IT','hacking','Hacking');
INSERT INTO Translations VALUES(NULL,'IT','adv','Pubblicità');
INSERT INTO Translations VALUES(NULL,'IT','hobby-games-online','Hobby/Giochi Online');
INSERT INTO Translations VALUES(NULL,'IT','dating','Incontri');
INSERT INTO Translations VALUES(NULL,'IT','porn','Siti per Adulti');
INSERT INTO Translations VALUES(NULL,'IT','hobby-gardening','Hobby/Giardinaggio');
INSERT INTO Translations VALUES(NULL,'IT','tracker','Tracker');
INSERT INTO Translations VALUES(NULL,'IT','finance-insurance','Finanza/Assicurazioni');
INSERT INTO Translations VALUES(NULL,'IT','finance-banking','Finanza/Banche');
INSERT INTO Translations VALUES(NULL,'IT','radiotv','Radio e TV');
INSERT INTO Translations VALUES(NULL,'IT','fortunetelling','Indovini');
INSERT INTO Translations VALUES(NULL,'IT','drugs','Droghe');
INSERT INTO Translations VALUES(NULL,'IT','finance-trading','Finanza/Borsa');
INSERT INTO Translations VALUES(NULL,'IT','hobby-games-misc','Hobby/Giochi Generici');
INSERT INTO Translations VALUES(NULL,'IT','imagehosting','Hosting Immagini');
INSERT INTO Translations VALUES(NULL,'IT','webmail','Webmail');
INSERT INTO Translations VALUES(NULL,'IT','isp','Provider Internet');
INSERT INTO Translations VALUES(NULL,'IT','science-chemistry','Scienza/Chimica');
INSERT INTO Translations VALUES(NULL,'IT','chat','Chat');
INSERT INTO Translations VALUES(NULL,'IT','recreation-sports','Ricreativi/Sport');
INSERT INTO Translations VALUES(NULL,'IT','recreation-restaurants','Ricreativi/Ristoranti');
INSERT INTO Translations VALUES(NULL,'IT','socialnet','Social Network');
INSERT INTO Translations VALUES(NULL,'IT','finance-other','Finanza/Altro');
INSERT INTO Translations VALUES(NULL,'IT','recreation-martialarts','Ricreativi/Arti Marziali');
INSERT INTO Translations VALUES(NULL,'IT','recreation-humor','Ricreativi/Comici');
INSERT INTO Translations VALUES(NULL,'IT','automobile-planes','Automobile/Aerei');
INSERT INTO Translations VALUES(NULL,'IT','dynamic','Indirizzi Dinamici');
INSERT INTO Translations VALUES(NULL,'IT','finance-realestate','Finanza/Appartamenti');
INSERT INTO Translations VALUES(NULL,'IT','library','Biblioteca');
INSERT INTO Translations VALUES(NULL,'IT','webphone','Telefonia su Internet');
INSERT INTO Translations VALUES(NULL,'IT','recreation-wellness','Ricreativi/Salute');
INSERT INTO Translations VALUES(NULL,'IT','searchengines','Motori di Ricerca');
INSERT INTO Translations VALUES(NULL,'IT','anonvpn','VPN anonimo ');
INSERT INTO Translations VALUES(NULL,'IT','education-schools','Scuole, colleggi e università');
INSERT INTO Translations VALUES(NULL,'IT','alcohol','Alcol');
INSERT INTO Translations VALUES(NULL,'IT','finance-moneylending','Finanza/Prestiti');
INSERT INTO Translations VALUES(NULL,'IT','automobile-cars','Automobile/Automobili');
INSERT INTO Translations VALUES(NULL,'IT','sex-education','Educazione Sessuale');
INSERT INTO Translations VALUES(NULL,'IT','remotecontrol','Controllo Remoto');
INSERT INTO Translations VALUES(NULL,'IT','forum','Forum');
INSERT INTO Translations VALUES(NULL,'IT','models','Modelle');
INSERT INTO Translations VALUES(NULL,'IT','ringtones','Suonerie');
INSERT INTO Translations VALUES(NULL,'IT','redirector','Proxy');
INSERT INTO Translations VALUES(NULL,'ES','sex-lingerie','Sex/Lenceria.');
INSERT INTO Translations VALUES(NULL,'ES','news','Noticias');
INSERT INTO Translations VALUES(NULL,'ES','shopping','Shopping');
INSERT INTO Translations VALUES(NULL,'ES','warez','Warez');
INSERT INTO Translations VALUES(NULL,'ES','hospitals','Hospitales');
INSERT INTO Translations VALUES(NULL,'ES','aggressive','Agresivo');
INSERT INTO Translations VALUES(NULL,'ES','downloads','Загрузка');
INSERT INTO Translations VALUES(NULL,'ES','spyware','Spyware');
INSERT INTO Translations VALUES(NULL,'ES','politics','Política');
INSERT INTO Translations VALUES(NULL,'ES','music','Música');
INSERT INTO Translations VALUES(NULL,'ES','hacking','Hacking');
INSERT INTO Translations VALUES(NULL,'ES','adv','Anuncios');
INSERT INTO Translations VALUES(NULL,'ES','hobby-games-online','Manía/Juegos-Online');
INSERT INTO Translations VALUES(NULL,'ES','dating','Dating');
INSERT INTO Translations VALUES(NULL,'ES','tracker','Tracker');
INSERT INTO Translations VALUES(NULL,'ES','hobby-games-misc','Manía/Juegos');
INSERT INTO Translations VALUES(NULL,'ES','webmail','Webmail');
INSERT INTO Translations VALUES(NULL,'ES','library','Biblioteca');
INSERT INTO Translations VALUES(NULL,'ES','anonvpn','VPN an?nimo');
INSERT INTO Translations VALUES(NULL,'ES','forum','Forum');
INSERT INTO Translations VALUES(NULL,'ES','models','Models');
INSERT INTO Translations VALUES(NULL,'ES','redirector','Proxy');
INSERT INTO Translations VALUES(NULL,'PT','news','Notícia');
INSERT INTO Translations VALUES(NULL,'PT','shopping','Shopping');
INSERT INTO Translations VALUES(NULL,'PT','warez','Warez');
INSERT INTO Translations VALUES(NULL,'PT','hospitals','Hospitais');
INSERT INTO Translations VALUES(NULL,'PT','aggressive','Aggressive');
INSERT INTO Translations VALUES(NULL,'PT','downloads','Transferências');
INSERT INTO Translations VALUES(NULL,'PT','spyware','Spyware');
INSERT INTO Translations VALUES(NULL,'PT','politics','Política');
INSERT INTO Translations VALUES(NULL,'PT','music','Música');
INSERT INTO Translations VALUES(NULL,'PT','hacking','Hacking');
INSERT INTO Translations VALUES(NULL,'PT','adv','Propagandas');
INSERT INTO Translations VALUES(NULL,'PT','hobby-games-online','Passatempo/Jogos-Online');
INSERT INTO Translations VALUES(NULL,'PT','dating','Dating');
INSERT INTO Translations VALUES(NULL,'PT','tracker','Tracker');
INSERT INTO Translations VALUES(NULL,'PT','hobby-games-misc','Passatempo/Jogos');
INSERT INTO Translations VALUES(NULL,'PT','webmail','Webmail');
INSERT INTO Translations VALUES(NULL,'PT','library','Biblioteca');
INSERT INTO Translations VALUES(NULL,'PT','forum','Forum');
INSERT INTO Translations VALUES(NULL,'PT','models','Models');
INSERT INTO Translations VALUES(NULL,'PT','redirector','Proxy');
INSERT INTO Translations VALUES(NULL,'FR','sex-lingerie','Sex/Dessous.');
INSERT INTO Translations VALUES(NULL,'FR','sex-lingerie-DESC','Sites de sexy dessous.');
INSERT INTO Translations VALUES(NULL,'FR','news','Nouvelles');
INSERT INTO Translations VALUES(NULL,'FR','religion','Religion');
INSERT INTO Translations VALUES(NULL,'FR','shopping','Shopping');
INSERT INTO Translations VALUES(NULL,'FR','shopping-DESC','Sites de vente et achat en ligne.');
INSERT INTO Translations VALUES(NULL,'FR','recreation-travel','Récréation/Voyage');
INSERT INTO Translations VALUES(NULL,'FR','warez','Warez');
INSERT INTO Translations VALUES(NULL,'FR','warez-DESC','Sites de logiciels pirates.');
INSERT INTO Translations VALUES(NULL,'FR','hospitals','Hôpitaux');
INSERT INTO Translations VALUES(NULL,'FR','aggressive','Agréssif ');
INSERT INTO Translations VALUES(NULL,'FR','aggressive-DESC','Quelques sites raçistes, antisémites, inçitant à la haine.');
INSERT INTO Translations VALUES(NULL,'FR','downloads','Téléchargements');
INSERT INTO Translations VALUES(NULL,'FR','webradio','Radio internet');
INSERT INTO Translations VALUES(NULL,'FR','webradio-DESC','Sites de radio sur Internet');
INSERT INTO Translations VALUES(NULL,'FR','politics','La politique');
INSERT INTO Translations VALUES(NULL,'FR','gamble','Jeux casino');
INSERT INTO Translations VALUES(NULL,'FR','gamble-DESC','Sites de jeux en ligne, casino, etc.');
INSERT INTO Translations VALUES(NULL,'FR','music','Musique');
INSERT INTO Translations VALUES(NULL,'FR','hacking','Hacking');
INSERT INTO Translations VALUES(NULL,'FR','adv','Annonces');
INSERT INTO Translations VALUES(NULL,'FR','adv-DESC','Vente et de Publicité: comprend des côtés, les bannières publicitaires insérer ainsi qu\'également entreprises publicitaires.');
INSERT INTO Translations VALUES(NULL,'FR','hobby-games-online-DESC','Sites de jeux, en ligne.');
INSERT INTO Translations VALUES(NULL,'FR','dating','Rencontre');
INSERT INTO Translations VALUES(NULL,'FR','dating-DESC','Sites de rencontres');
INSERT INTO Translations VALUES(NULL,'FR','movies','Vidéo');
INSERT INTO Translations VALUES(NULL,'FR','movies-DESC','Quelques sites orientés vers la vidéo.');
INSERT INTO Translations VALUES(NULL,'FR','porn','Adulte');
INSERT INTO Translations VALUES(NULL,'FR','porn-DESC','Des sites adultes allant de l\'érotique à la pornographie dure.');
INSERT INTO Translations VALUES(NULL,'FR','drugs','Drogue');
INSERT INTO Translations VALUES(NULL,'FR','hobby-games-misc-DESC','Sites de distributions de jeux.');
INSERT INTO Translations VALUES(NULL,'FR','webmail','Messagerie Web');
INSERT INTO Translations VALUES(NULL,'FR','webmail-DESC','Webmail que l\'on trouve sur internet (hotmail, webmail.univ-tlse1.fr, etc.)');
INSERT INTO Translations VALUES(NULL,'FR','recreation-sports','Récréation/Sports');
INSERT INTO Translations VALUES(NULL,'FR','recreation-martialarts','Récréation/Arts Martiaux');
INSERT INTO Translations VALUES(NULL,'FR','recreation-wellness','Récréation/Santé');
INSERT INTO Translations VALUES(NULL,'FR','anonvpn','VPN anonyme');
INSERT INTO Translations VALUES(NULL,'FR','forum','Forum');
INSERT INTO Translations VALUES(NULL,'FR','models','Models');
INSERT INTO Translations VALUES(NULL,'FR','redirector','Proxy');
INSERT INTO Translations VALUES(NULL,'FR','redirector-DESC','Quelques sites qui permettent de contourner les filtres.');
INSERT INTO Translations VALUES(NULL,'EN','good','Whitelist');
INSERT INTO Translations VALUES(NULL,'EN','good-DESC','Own Whitelist');
INSERT INTO Translations VALUES(NULL,'EN','bad','Blacklist');
INSERT INTO Translations VALUES(NULL,'EN','bad-DESC','Own Blacklist');
INSERT INTO Translations VALUES(NULL,'EN','all','The Rest');
INSERT INTO Translations VALUES(NULL,'EN','all-DESC','All other domains');
INSERT INTO Translations VALUES(NULL,'EN','in-addr','IP-Addresses');
INSERT INTO Translations VALUES(NULL,'EN','in-addr-DESC','IP-Addresses');
INSERT INTO Translations VALUES(NULL,'EN','costtraps','Cost Traps');
INSERT INTO Translations VALUES(NULL,'EN','costtraps-DESC','Sites that lure with free of charge services but then give then give you a costly subscription (written somewhere in tiny letters nearly unreadable).');
INSERT INTO Translations VALUES(NULL,'EN','sex-lingerie','Sex/Lingerie.');
INSERT INTO Translations VALUES(NULL,'EN','sex-lingerie-DESC','Sites selling and presenting sexy lingerie.');
INSERT INTO Translations VALUES(NULL,'EN','weapons','Weapons');
INSERT INTO Translations VALUES(NULL,'EN','weapons-DESC','Sites offering all kinds of weapons or accessories for weapons: Firearms, knifes, swords, bows, etc. Armory shops are included as well as sites holding general information about arms (manufacturing, usage).');
INSERT INTO Translations VALUES(NULL,'EN','updatesites','Update Sites');
INSERT INTO Translations VALUES(NULL,'EN','updatesites-DESC','List to allow necessary downloads from vendors.');
INSERT INTO Translations VALUES(NULL,'EN','news','News');
INSERT INTO Translations VALUES(NULL,'EN','news-DESC','Sites presenting news. Homepages from newspapers, magazines and journals as well as some blogs.');
INSERT INTO Translations VALUES(NULL,'EN','religion','Religion');
INSERT INTO Translations VALUES(NULL,'EN','religion-DESC','Sites with religious content: all kind of churches, sects, religious interpretations, etc.');
INSERT INTO Translations VALUES(NULL,'EN','shopping','Shopping');
INSERT INTO Translations VALUES(NULL,'EN','shopping-DESC','Sites offering online shopping and price comparisons.');
INSERT INTO Translations VALUES(NULL,'EN','violence','Violence');
INSERT INTO Translations VALUES(NULL,'EN','violence-DESC','Sites about killing and harming people. Covers anything about brutality and beastiality.');
INSERT INTO Translations VALUES(NULL,'EN','hobby-pets','Hobby/Pets');
INSERT INTO Translations VALUES(NULL,'EN','hobby-pets-DESC','All topics concerning pets: description, breed, food, looks, fairs, favorite pet stories and so on.');
INSERT INTO Translations VALUES(NULL,'EN','webtv','Web TV, Internet TV');
INSERT INTO Translations VALUES(NULL,'EN','webtv-DESC','Sites offering TV streams via Internet.');
INSERT INTO Translations VALUES(NULL,'EN','automobile-boats','Automobil/Boats');
INSERT INTO Translations VALUES(NULL,'EN','automobile-boats-DESC','All sites related motorboats. Included are vendor sites, resellers, fan and hobby pages as well as and suppliers.');
INSERT INTO Translations VALUES(NULL,'EN','recreation-travel','Recreation/Travel');
INSERT INTO Translations VALUES(NULL,'EN','recreation-travel-DESC','Sites with information about foreign countries, travel companies, travel fares, accommodations and everything else that has to do with travel.');
INSERT INTO Translations VALUES(NULL,'EN','warez','Warez');
INSERT INTO Translations VALUES(NULL,'EN','warez-DESC','Collection of sites offering programs to break licence keys, licence keys themselves, cracked software and other copyrighted material.');
INSERT INTO Translations VALUES(NULL,'EN','hospitals','Hospitals');
INSERT INTO Translations VALUES(NULL,'EN','hospitals-DESC','Sites of hospitals and medical facilities.');
INSERT INTO Translations VALUES(NULL,'EN','aggressive','Aggressive');
INSERT INTO Translations VALUES(NULL,'EN','aggressive-DESC','Sites with aggressive content such as racism and hate speech.');
INSERT INTO Translations VALUES(NULL,'EN','downloads','Downloads');
INSERT INTO Translations VALUES(NULL,'EN','downloads-DESC','This covers mostly filesharing, p2p and torrent sites. Other download sites (for software, wallpapers, ..) are included as well.');
INSERT INTO Translations VALUES(NULL,'EN','homestyle','Homestyle');
INSERT INTO Translations VALUES(NULL,'EN','homestyle-DESC','Sites about everything need to create a cozy home (interior design and accessories).');
INSERT INTO Translations VALUES(NULL,'EN','spyware','Spyware');
INSERT INTO Translations VALUES(NULL,'EN','spyware-DESC','Sites that try to actively install software or lure the user in doing so in order to spy the surfing behaviour (or worse). The home calling sites where the collected information is sent, are listed too.');
INSERT INTO Translations VALUES(NULL,'EN','webradio','Internet radios');
INSERT INTO Translations VALUES(NULL,'EN','webradio-DESC','Sites that offer listening to music and radio live streams.');
INSERT INTO Translations VALUES(NULL,'EN','government','Government');
INSERT INTO Translations VALUES(NULL,'EN','government-DESC','Sites belonging to the government of a country, county or city.');
INSERT INTO Translations VALUES(NULL,'EN','politics','Politics');
INSERT INTO Translations VALUES(NULL,'EN','politics-DESC','Sites of political parties, political organisations and associations; sites with political discussions.');
INSERT INTO Translations VALUES(NULL,'EN','hobby-cooking','Hobby/Cooking');
INSERT INTO Translations VALUES(NULL,'EN','hobby-cooking-DESC','Sites concerning food and food preparation.');
INSERT INTO Translations VALUES(NULL,'EN','podcasts','Podcasts');
INSERT INTO Translations VALUES(NULL,'EN','podcasts-DESC','Sites offering podcasts or podcast services, includes audio books.');
INSERT INTO Translations VALUES(NULL,'EN','gamble','Gambling/Casino');
INSERT INTO Translations VALUES(NULL,'EN','gamble-DESC','Sites offering the possibility to win money. Poker, Casino, Bingo and other chance games as well as betting sites.');
INSERT INTO Translations VALUES(NULL,'EN','automobile-bikes','Automobile/Bikes');
INSERT INTO Translations VALUES(NULL,'EN','automobile-bikes-DESC','All sites related to motorcycles. Included are vendor sites, resellers, fan and hobby pages as well as and suppliers. Scooters included.');
INSERT INTO Translations VALUES(NULL,'EN','jobsearch','Jobsearch');
INSERT INTO Translations VALUES(NULL,'EN','jobsearch-DESC','Portals for job offers and job seekers as well as the career and work-for-us pages of companies.');
INSERT INTO Translations VALUES(NULL,'EN','military','Military');
INSERT INTO Translations VALUES(NULL,'EN','military-DESC','Sites of military facilities or related to the armed forces.');
INSERT INTO Translations VALUES(NULL,'EN','music','Music');
INSERT INTO Translations VALUES(NULL,'EN','music-DESC','Sites that offer the download of music, information about music groups or music in general.');
INSERT INTO Translations VALUES(NULL,'EN','science-astronomy','Science/Astronomy');
INSERT INTO Translations VALUES(NULL,'EN','science-astronomy-DESC','Sites of institutions as well as of amateurs about all topics of astronomy.');
INSERT INTO Translations VALUES(NULL,'EN','hacking','Hacking');
INSERT INTO Translations VALUES(NULL,'EN','hacking-DESC','Sites with information and discussions about security weaknesses and how to exploit them. Sites offering exploits are listed as well as sites distributing programs that help to find security leaks.');
INSERT INTO Translations VALUES(NULL,'EN','adv','Advertisements');
INSERT INTO Translations VALUES(NULL,'EN','adv-DESC','All about advertising: This includes sites offering banners and banner creation as well as sites delivering banners to be shown in webpages and advertising companies.');
INSERT INTO Translations VALUES(NULL,'EN','hobby-games-online','Hobby/Online-Games');
INSERT INTO Translations VALUES(NULL,'EN','hobby-games-online-DESC','Sites about online games. The games are for fun only (no gambling).');
INSERT INTO Translations VALUES(NULL,'EN','dating','Dating');
INSERT INTO Translations VALUES(NULL,'EN','dating-DESC','Sites to contact people for love and living together. He seeks her, she seeks him and so on.');
INSERT INTO Translations VALUES(NULL,'EN','movies','Movies and Videos');
INSERT INTO Translations VALUES(NULL,'EN','movies-DESC','Sites offering cinema programs, information about movies and actors. Sites for downloading video clips/movies (as long as it is legal) are included as well.');
INSERT INTO Translations VALUES(NULL,'EN','porn','Porn');
INSERT INTO Translations VALUES(NULL,'EN','porn-DESC','Sites about all kinds of sexual content ranging from bare bosoms to hardcore porn and sm.');
INSERT INTO Translations VALUES(NULL,'EN','hobby-gardening','Hobby/Gardening');
INSERT INTO Translations VALUES(NULL,'EN','hobby-gardening-DESC','Sites about gardening, growing plants, fighting bugs and everything related to gardening.');
INSERT INTO Translations VALUES(NULL,'EN','tracker','Tracker');
INSERT INTO Translations VALUES(NULL,'EN','tracker-DESC','Sites keeping an eye on where you surf and what you do in a passive manner. Covers web bugs, counters and other tracking mechanisms in web pages that do not interfere with the local computer yet collect information about the surfing person for later analysis.');
INSERT INTO Translations VALUES(NULL,'EN','finance-insurance','Finance/Insurance');
INSERT INTO Translations VALUES(NULL,'EN','finance-insurance-DESC','Sites of insurance companies, information about insurances and link collections concering this subject.');
INSERT INTO Translations VALUES(NULL,'EN','finance-banking','Finance/Banking');
INSERT INTO Translations VALUES(NULL,'EN','finance-banking-DESC','Home page of banking companies are listed here. This is not restricted to online banking.');
INSERT INTO Translations VALUES(NULL,'EN','radiotv','Radio and TV');
INSERT INTO Translations VALUES(NULL,'EN','radiotv-DESC','Domains and urls of TV and radio stations.');
INSERT INTO Translations VALUES(NULL,'EN','fortunetelling','Fortune telling');
INSERT INTO Translations VALUES(NULL,'EN','fortunetelling-DESC','All sites about astrology, horoscopes, numerology, palm reading and so on; sites that offer services to fortell the future.');
INSERT INTO Translations VALUES(NULL,'EN','drugs','Drugs');
INSERT INTO Translations VALUES(NULL,'EN','drugs-DESC','Sites offering drugs or explain how to make drugs. Covers alcohol and tobacco as well as viagra and similar substances.');
INSERT INTO Translations VALUES(NULL,'EN','finance-trading','Finance/Trading');
INSERT INTO Translations VALUES(NULL,'EN','finance-trading-DESC','Sites about and related to stock exchange.');
INSERT INTO Translations VALUES(NULL,'EN','hobby-games-misc','Hobby/Games');
INSERT INTO Translations VALUES(NULL,'EN','hobby-games-misc-DESC','Sites related to games. This includes descriptions, news and general information about games. No gambling sites.');
INSERT INTO Translations VALUES(NULL,'EN','imagehosting','Imagehosting');
INSERT INTO Translations VALUES(NULL,'EN','imagehosting-DESC','Sites specialized on hosting images, photo galleries and so on.');
INSERT INTO Translations VALUES(NULL,'EN','webmail','Webmail');
INSERT INTO Translations VALUES(NULL,'EN','webmail-DESC','Sites that offer web-based email services.');
INSERT INTO Translations VALUES(NULL,'EN','isp','Internet Service Provider');
INSERT INTO Translations VALUES(NULL,'EN','isp-DESC','Home pages of Internet Service Providers. Sites of companies offering webspace only are now being added, too');
INSERT INTO Translations VALUES(NULL,'EN','science-chemistry','Science/Chemistry');
INSERT INTO Translations VALUES(NULL,'EN','science-chemistry-DESC','Sites of institutions as well as of amateurs about all topics of chemistry.');
INSERT INTO Translations VALUES(NULL,'EN','chat','Chat');
INSERT INTO Translations VALUES(NULL,'EN','chat-DESC','Site for real-time chatting and instant messaging.');
INSERT INTO Translations VALUES(NULL,'EN','recreation-sports','Recreation/Sports');
INSERT INTO Translations VALUES(NULL,'EN','recreation-sports-DESC','All about sports: sports teams, sport discussions as well as information about sports people and the various sports themselves.');
INSERT INTO Translations VALUES(NULL,'EN','recreation-restaurants','Recreation/Restaurants');
INSERT INTO Translations VALUES(NULL,'EN','recreation-restaurants-DESC','Sites of restaurants as well as restaurant descriptions and commentaries.');
INSERT INTO Translations VALUES(NULL,'EN','socialnet','Social Networking');
INSERT INTO Translations VALUES(NULL,'EN','socialnet-DESC','Sites bringing people together (social networking) be it for friendship or for business.');
INSERT INTO Translations VALUES(NULL,'EN','finance-other','Finance/Other');
INSERT INTO Translations VALUES(NULL,'EN','finance-other-DESC','Finance in general.');
INSERT INTO Translations VALUES(NULL,'EN','recreation-martialarts','Recreation/Martialarts');
INSERT INTO Translations VALUES(NULL,'EN','recreation-martialarts-DESC','Sites dedicated to martial arts such as: karate, kung fu, taek won do as well as fighting sports sites like ufc.');
INSERT INTO Translations VALUES(NULL,'EN','recreation-humor','Recreation/Humor');
INSERT INTO Translations VALUES(NULL,'EN','recreation-humor-DESC','Humorous pages, comic strips, funny stories, everything which makes people laugh.');
INSERT INTO Translations VALUES(NULL,'EN','automobile-planes','Automobile/Planes');
INSERT INTO Translations VALUES(NULL,'EN','automobile-planes-DESC','All sites related to planes ranging from small one and two seaters up to the large traffic planes, old and new, private, commercial and military. Vendors and supplier are included (airports are not). Helicopter sites are included as well.');
INSERT INTO Translations VALUES(NULL,'EN','dynamic','Dynamic (Dialup) Addresses');
INSERT INTO Translations VALUES(NULL,'EN','dynamic-DESC','All domains where people login obtaining a dynamic IP address.');
INSERT INTO Translations VALUES(NULL,'EN','finance-realestate','Finance/Realestate');
INSERT INTO Translations VALUES(NULL,'EN','finance-realestate-DESC','Sites about all types of real estate, buying and selling homes, finding apartments for rent.');
INSERT INTO Translations VALUES(NULL,'EN','library','Library');
INSERT INTO Translations VALUES(NULL,'EN','library-DESC','Online libraries and sites where you can read e-books.');
INSERT INTO Translations VALUES(NULL,'EN','webphone','Internet Phone');
INSERT INTO Translations VALUES(NULL,'EN','webphone-DESC','Sites that enable user to phone via the Internet. Any site where users can voice-chat with each other.');
INSERT INTO Translations VALUES(NULL,'EN','recreation-wellness','Recreation/Wellness');
INSERT INTO Translations VALUES(NULL,'EN','recreation-wellness-DESC','Sites about treatments for feeling internally and externally healthy and beautiful again.');
INSERT INTO Translations VALUES(NULL,'EN','searchengines','Searchengines');
INSERT INTO Translations VALUES(NULL,'EN','searchengines-DESC','Collection of search engines and directory sites.');
INSERT INTO Translations VALUES(NULL,'EN','anonvpn','Anonymous VPN');
INSERT INTO Translations VALUES(NULL,'EN','anonvpn-DESC','Sites providing vpn services to the public. The focus is on vpn sites used to hide the origin of the traffic, f.e. tor nodes.');
INSERT INTO Translations VALUES(NULL,'EN','education-schools','Schools');
INSERT INTO Translations VALUES(NULL,'EN','education-schools-DESC','Home pages of schools, colleges and universities.');
INSERT INTO Translations VALUES(NULL,'EN','alcohol','Alcohol');
INSERT INTO Translations VALUES(NULL,'EN','alcohol-DESC','Sites of breweries, wineries and destilleries. This category also covers sites that explain how to make beer, wines and spirits.');
INSERT INTO Translations VALUES(NULL,'EN','finance-moneylending','Finance/Moneylending');
INSERT INTO Translations VALUES(NULL,'EN','finance-moneylending-DESC','Sites one can apply for loans and mortgages or can obtain information about this business.');
INSERT INTO Translations VALUES(NULL,'EN','automobile-cars','Automobile/Cars');
INSERT INTO Translations VALUES(NULL,'EN','automobile-cars-DESC','All sites related to cars. Included are automobile companies and automotive suppliers.');
INSERT INTO Translations VALUES(NULL,'EN','sex-education','Sex/Education.');
INSERT INTO Translations VALUES(NULL,'EN','sex-education-DESC','Sites explaining the biological functions of the body concerning sexuality as well as sexual health.');
INSERT INTO Translations VALUES(NULL,'EN','remotecontrol','Remote Control');
INSERT INTO Translations VALUES(NULL,'EN','remotecontrol-DESC','Sites offering the service to remotely access computers, especially (but not limited to going) through firewalls. This does not cover traditional VPN.');
INSERT INTO Translations VALUES(NULL,'EN','forum','Forum');
INSERT INTO Translations VALUES(NULL,'EN','forum-DESC','Discussion sites. Covers explicit forum sites and some blogs. Sites where people can discuss and share information in a non interactive/real-time way.');
INSERT INTO Translations VALUES(NULL,'EN','urlshortener','URL shortener');
INSERT INTO Translations VALUES(NULL,'EN','urlshortener-DESC','Sites offering short links for URLs. ');
INSERT INTO Translations VALUES(NULL,'EN','models','Models');
INSERT INTO Translations VALUES(NULL,'EN','models-DESC','Model agency, model and supermodel fan pages and other model sites presenting model photos. No porn pictures.');
INSERT INTO Translations VALUES(NULL,'EN','ringtones','Ringtones');
INSERT INTO Translations VALUES(NULL,'EN','ringtones-DESC','Sites that offer the download of ringtones or present other information about ringtones.');
INSERT INTO Translations VALUES(NULL,'EN','redirector','Proxy');
INSERT INTO Translations VALUES(NULL,'EN','redirector-DESC','Sites that actively help to bypass url filters by accepting urls via form and play a proxing and redirecting role.');
INSERT INTO Translations VALUES(NULL,'DE','good','Whiteliste');
INSERT INTO Translations VALUES(NULL,'DE','good-DESC','Eigene Whiteliste');
INSERT INTO Translations VALUES(NULL,'DE','bad','Blackliste');
INSERT INTO Translations VALUES(NULL,'DE','bad-DESC','Eigene Blackliste');
INSERT INTO Translations VALUES(NULL,'DE','all','Der Rest');
INSERT INTO Translations VALUES(NULL,'DE','all-DESC','Alle andere Domains');
INSERT INTO Translations VALUES(NULL,'DE','in-addr','IP-Adressen');
INSERT INTO Translations VALUES(NULL,'DE','in-addr-DESC','IP-Adressen');
INSERT INTO Translations VALUES(NULL,'DE','costtraps','Kostenfallen');
INSERT INTO Translations VALUES(NULL,'DE','costtraps-DESC','Seiten mit undurchsichtiger Preisgestaltung: scheinbar kostenlose Dienste, die jedoch in einem kostenpflichtigen Abbonement enden (in kleinster Schrift unleserlich dargelegt).');
INSERT INTO Translations VALUES(NULL,'DE','sex-lingerie','Sex/Reizwäsche.');
INSERT INTO Translations VALUES(NULL,'DE','sex-lingerie-DESC','Seiten, auf denen Reizwäsche präsnetiert und angeboten wird.');
INSERT INTO Translations VALUES(NULL,'DE','weapons','Waffen');
INSERT INTO Translations VALUES(NULL,'DE','weapons-DESC','Waffen und Zubehör. Seiten, die Funktionsweise und den Umgang mit Waffen erklären sowie Hersteller.');
INSERT INTO Translations VALUES(NULL,'DE','updatesites','Software Aktualisierungen');
INSERT INTO Translations VALUES(NULL,'DE','updatesites-DESC','Herstellerseiten für Software Aktualisierungen.');
INSERT INTO Translations VALUES(NULL,'DE','news','Nachrichten');
INSERT INTO Translations VALUES(NULL,'DE','news-DESC','Nachrichtenmagazine, Journale und einige Blogs.');
INSERT INTO Translations VALUES(NULL,'DE','religion','Religion');
INSERT INTO Translations VALUES(NULL,'DE','religion-DESC','Seiten mit religiösem Inhalt: Jegliche Art von Kirchen, Sekten, religiöse Interpretationen usw.');
INSERT INTO Translations VALUES(NULL,'DE','shopping','Einkaufen');
INSERT INTO Translations VALUES(NULL,'DE','shopping-DESC','Seiten für Käufe via Internet und Preisvergleiche.');
INSERT INTO Translations VALUES(NULL,'DE','violence','Gewalt');
INSERT INTO Translations VALUES(NULL,'DE','violence-DESC','Gewalt und Gewaltverherrlichung. Beinhaltet Darstellungen des gewaltsamen Todes von Menschen, wie man anderen Schaden zufügt, Brutalität und Bestialität.');
INSERT INTO Translations VALUES(NULL,'DE','hobby-pets','Hobby/Haustiere');
INSERT INTO Translations VALUES(NULL,'DE','hobby-pets-DESC','Seiten über Haustiere, Haustierhaltung, Pflegetips, etc.');
INSERT INTO Translations VALUES(NULL,'DE','webtv','Internet Fernsehen');
INSERT INTO Translations VALUES(NULL,'DE','webtv-DESC','Seiten, die Fernsehen per WWW anbieten.');
INSERT INTO Translations VALUES(NULL,'DE','automobile-boats','Automobil/Boote');
INSERT INTO Translations VALUES(NULL,'DE','automobile-boats-DESC','Alles zur Thematik Motorboote; Bezug, Typen, Hersteller, Zulieferer, Wartung und Pflege.');
INSERT INTO Translations VALUES(NULL,'DE','recreation-travel','Entspannung/Reisen');
INSERT INTO Translations VALUES(NULL,'DE','recreation-travel-DESC','Reiseveranstalter, Reisebeschreibungen, Hotels, Buchungen, Fluggesellschaften, Bahn und ähnliches: alles, was man zum Reisen wissen muss oder möchte.');
INSERT INTO Translations VALUES(NULL,'DE','warez','Warez');
INSERT INTO Translations VALUES(NULL,'DE','warez-DESC','Seiten, die geknackte Passworte und Lizenzen kopiergeschützter Programme anbieten sowie das Laden kopiergeschützten Daten und Programme.');
INSERT INTO Translations VALUES(NULL,'DE','hospitals','Krankenhäuser');
INSERT INTO Translations VALUES(NULL,'DE','hospitals-DESC','Seiten von Krankenhäusern und medizinischen Einrichtungen.');
INSERT INTO Translations VALUES(NULL,'DE','aggressive','Aggressiv');
INSERT INTO Translations VALUES(NULL,'DE','aggressive-DESC','Agressive Inhalte wie Rassismus, Beleidungen, Hassreden.');
INSERT INTO Translations VALUES(NULL,'DE','downloads','Downloads');
INSERT INTO Translations VALUES(NULL,'DE','downloads-DESC','Herunterladen von Software, Bilder, u.ä. sei es direkt oder über P2P/Torrent Seiten.');
INSERT INTO Translations VALUES(NULL,'DE','homestyle','Schöner Wohnen');
INSERT INTO Translations VALUES(NULL,'DE','homestyle-DESC','Seiten bzgl. Inneneinrichtungen; alles, was ein Heim heimelig und angenehm macht.');
INSERT INTO Translations VALUES(NULL,'DE','spyware','Spyware');
INSERT INTO Translations VALUES(NULL,'DE','webradio','Internet Radio');
INSERT INTO Translations VALUES(NULL,'DE','webradio-DESC','Seiten mit Internet Radio und Audio Live Streams.');
INSERT INTO Translations VALUES(NULL,'DE','government','Behörden');
INSERT INTO Translations VALUES(NULL,'DE','government-DESC','Behördenseiten.');
INSERT INTO Translations VALUES(NULL,'DE','politics','Politik');
INSERT INTO Translations VALUES(NULL,'DE','politics-DESC','Seiten politischer Parteien und politischer Organisationen; Seiten mit politischen Diskussionen.');
INSERT INTO Translations VALUES(NULL,'DE','hobby-cooking','Hobby/Kochen');
INSERT INTO Translations VALUES(NULL,'DE','hobby-cooking-DESC','Seiten über Nahrungsmittel und ihre Zubereitung.');
INSERT INTO Translations VALUES(NULL,'DE','podcasts','Podcasts');
INSERT INTO Translations VALUES(NULL,'DE','podcasts-DESC','Seiten mit podcasts oder Podcast Angeboten; beinhaltet auch Hörbücher.');
INSERT INTO Translations VALUES(NULL,'DE','gamble','Wetten/Glueckspiel ');
INSERT INTO Translations VALUES(NULL,'DE','gamble-DESC','Glückspiel und Wett-Seiten.');
INSERT INTO Translations VALUES(NULL,'DE','automobile-bikes','Automobil/Motorräder');
INSERT INTO Translations VALUES(NULL,'DE','automobile-bikes-DESC','Rund um das Motorad: Hersteller, Zulieferer, Reparaturen u.ä.');
INSERT INTO Translations VALUES(NULL,'DE','jobsearch','Arbeitssuche');
INSERT INTO Translations VALUES(NULL,'DE','jobsearch-DESC','Arbeitsportale für Arbeitssuchende und Arbeitgeber. Beinhaltet auch Karriereberatungen.');
INSERT INTO Translations VALUES(NULL,'DE','military','Militär');
INSERT INTO Translations VALUES(NULL,'DE','military-DESC','Seiten militärischer Einrichtungen bzw. jene, die mit der Armee im Zusammenhang stehen.');
INSERT INTO Translations VALUES(NULL,'DE','music','Musik');
INSERT INTO Translations VALUES(NULL,'DE','music-DESC','Musik zum Download, Informationen zu Musik und Musikgruppen, Musik im allgemeinen.');
INSERT INTO Translations VALUES(NULL,'DE','science-astronomy','Wissenschaft/Astronomie');
INSERT INTO Translations VALUES(NULL,'DE','science-astronomy-DESC','Astronomie und Astrophysik sowohl aus dem Amateur- wie auch aus dem professionellen Umfeld.');
INSERT INTO Translations VALUES(NULL,'DE','hacking','Hacking');
INSERT INTO Translations VALUES(NULL,'DE','hacking-DESC','Informationen über Sicherheitsschwächen und wie man sie ausnutzt. Seiten, die Programme zum Ausnutzen von Sicherheitsschwächen bieten.');
INSERT INTO Translations VALUES(NULL,'DE','adv','Werbung');
INSERT INTO Translations VALUES(NULL,'DE','adv-DESC','Werbe- und Markeingseiten: Beinhaltet Seiten, die Werbebanner einblenden sowie auch Werbefirmen.');
INSERT INTO Translations VALUES(NULL,'DE','hobby-games-online','Hobby/Online-Spiele');
INSERT INTO Translations VALUES(NULL,'DE','hobby-games-online-DESC','Seiten, die Online-Spiele (flash u.ä.) ohne Geldeinsatz (keine Eetten) anbieten. Spiele zum reinen Spass.');
INSERT INTO Translations VALUES(NULL,'DE','dating','Kontaktbörsen');
INSERT INTO Translations VALUES(NULL,'DE','dating-DESC','Kontaktbörsen für das Leben zu zweit.');
INSERT INTO Translations VALUES(NULL,'DE','movies','Filme');
INSERT INTO Translations VALUES(NULL,'DE','movies-DESC','Kinoprogramme und Informationen über Filme und Darsteller. Laden von Video Clips und Filmen (solange dies legal ist).');
INSERT INTO Translations VALUES(NULL,'DE','porn','Pornographie');
INSERT INTO Translations VALUES(NULL,'DE','porn-DESC','Seiten mit erotischem und pornographischem Inhalt.');
INSERT INTO Translations VALUES(NULL,'DE','hobby-gardening','Hobby/Gärtnern');
INSERT INTO Translations VALUES(NULL,'DE','hobby-gardening-DESC','Seiten über das Gärtnern, wie man Pflanzenn züchtet, Ungeziefer bekämft und alle mit dem Thema Gärtnern verwandten Themen.');
INSERT INTO Translations VALUES(NULL,'DE','tracker','Tracker');
INSERT INTO Translations VALUES(NULL,'DE','tracker-DESC','Passives Ausspähen des Benutzerverhaltens. Beinhaltet tracking cookies, web bugs, Zähler u.ä., die in Webseiten zur Analyse der Benutzerverhaltens untergebracht sind.');
INSERT INTO Translations VALUES(NULL,'DE','finance-insurance','Finanzen/Versicherungen');
INSERT INTO Translations VALUES(NULL,'DE','finance-insurance-DESC','Alles zur Thematik Versicherungen und Versicherer.');
INSERT INTO Translations VALUES(NULL,'DE','finance-banking','Finanzen/Banken');
INSERT INTO Translations VALUES(NULL,'DE','radiotv','TV und Radio');
INSERT INTO Translations VALUES(NULL,'DE','radiotv-DESC','Domänen und URLs von Radio- und Fernsehstationen.');
INSERT INTO Translations VALUES(NULL,'DE','fortunetelling','Wahrsagerei');
INSERT INTO Translations VALUES(NULL,'DE','fortunetelling-DESC','Seiten über Astrologie, Horoskope, Nummerologie, Handlesen usw.; Seiten, die Dienste bzgl. Wahrsagerei und der Zukunftsvorhersage anbieten.');
INSERT INTO Translations VALUES(NULL,'DE','drugs','Drogen');
INSERT INTO Translations VALUES(NULL,'DE','drugs-DESC','Seiten, die Drogen und Medikamente anbieten. Beinhaltet auch Alkohol, Zigaretten und Viagra, Cialis, etc.');
INSERT INTO Translations VALUES(NULL,'DE','finance-trading','Finanzen/Börse');
INSERT INTO Translations VALUES(NULL,'DE','finance-trading-DESC','Seite über die Börse und den Börsenhandel (Aktien, Optionen usw.).');
INSERT INTO Translations VALUES(NULL,'DE','hobby-games-misc','Hobby/Spiele');
INSERT INTO Translations VALUES(NULL,'DE','hobby-games-misc-DESC','Seiten über Beschreibeungen, Neuigkeiten und allgemeinen Informationen zu Spielen ohne Geldeinsatz (keine Wetten).');
INSERT INTO Translations VALUES(NULL,'DE','imagehosting','Bildergalerien');
INSERT INTO Translations VALUES(NULL,'DE','imagehosting-DESC','Seiten, die insbesondere alle Arten von Bildern und Graphiken hosten, auch Photogallerien und ähnliches.');
INSERT INTO Translations VALUES(NULL,'DE','webmail','Webmail');
INSERT INTO Translations VALUES(NULL,'DE','webmail-DESC','Seiten die web-basierte E-Mail Dienste anbieten.');
INSERT INTO Translations VALUES(NULL,'DE','isp','Internet Service Provider');
INSERT INTO Translations VALUES(NULL,'DE','isp-DESC','Seiten von Internet Service Providern; beinhaltet auch Seiten von reinen Webspaceanbietern.');
INSERT INTO Translations VALUES(NULL,'DE','science-chemistry','Wissenschaft/Chemie');
INSERT INTO Translations VALUES(NULL,'DE','science-chemistry-DESC','Rund um die Wissenschaft Chemie: Institutionen und Lehrhaftes.');
INSERT INTO Translations VALUES(NULL,'DE','chat','Chat');
INSERT INTO Translations VALUES(NULL,'DE','chat-DESC','Plaudern via Internet in Echtzeit.');
INSERT INTO Translations VALUES(NULL,'DE','recreation-sports','Entspannung/Sport');
INSERT INTO Translations VALUES(NULL,'DE','recreation-restaurants','Entspannung/Restaurants');
INSERT INTO Translations VALUES(NULL,'DE','recreation-restaurants-DESC','Seiten von Restaurant, Restaurantbeschreibungen und -rezensionen.');
INSERT INTO Translations VALUES(NULL,'DE','socialnet','Social Networking');
INSERT INTO Translations VALUES(NULL,'DE','finance-other','Finanzen/Allgemein');
INSERT INTO Translations VALUES(NULL,'DE','finance-other-DESC','Seiten, die ganz allgemein mit Finanzen zu tun haben (Wechselkurse, Anlegertips u.ä.).');
INSERT INTO Translations VALUES(NULL,'DE','recreation-martialarts','Entspannung/Kampfsport');
INSERT INTO Translations VALUES(NULL,'DE','recreation-martialarts-DESC','Seiten über alle Arten von Kampfsport, z.B. Kung-Fu, Taek Won Do, Karate, aber auch Kick-Boxen und ähnliches.');
INSERT INTO Translations VALUES(NULL,'DE','recreation-humor','Entspannung/Humor');
INSERT INTO Translations VALUES(NULL,'DE','recreation-humor-DESC','Alles, was zum Schmunzlen und Lachen bringt.');
INSERT INTO Translations VALUES(NULL,'DE','automobile-planes','Automobil/Flugzeuge');
INSERT INTO Translations VALUES(NULL,'DE','dynamic','Dynamische Adressen');
INSERT INTO Translations VALUES(NULL,'DE','dynamic-DESC','Domänen, die direkt dynamischen IP Bereichen zugeordnet sind; typischerweise die Zugänge von Endbenutzern.');
INSERT INTO Translations VALUES(NULL,'DE','finance-realestate','Finanzen/Immobilien');
INSERT INTO Translations VALUES(NULL,'DE','finance-realestate-DESC','Seite über alle Arten von Immobilien, Kauf und Verkauf von Wohnungen und Häusern, auch Mietmarkt.');
INSERT INTO Translations VALUES(NULL,'DE','library','Bibliotheken');
INSERT INTO Translations VALUES(NULL,'DE','library-DESC','Online Bibliotheken und Seiten zum Lesen von Büchern (e-books).');
INSERT INTO Translations VALUES(NULL,'DE','webphone','Internet Telephonie');
INSERT INTO Translations VALUES(NULL,'DE','webphone-DESC','Seiten, die Internet Telephonie, speziell, aber nicht nur http basiert, anbieten.');
INSERT INTO Translations VALUES(NULL,'DE','recreation-wellness','Entspannung/Wellness');
INSERT INTO Translations VALUES(NULL,'DE','recreation-wellness-DESC','Wellness: Alles, was Körper und Seele gut tut.');
INSERT INTO Translations VALUES(NULL,'DE','searchengines','Suchmaschinen');
INSERT INTO Translations VALUES(NULL,'DE','searchengines-DESC','Suchmaschinen und Verzeichnisseiten.');
INSERT INTO Translations VALUES(NULL,'DE','anonvpn','Anonymes VPN');
INSERT INTO Translations VALUES(NULL,'DE','anonvpn-DESC','Seiten, die VPN Dienste anbieten (keine Firmen-VPNs). Es betrifft haupts?chlich Seiten, die den Ursprung der Kommunikation verschleiern wie z.B. Tor Knoten.');
INSERT INTO Translations VALUES(NULL,'DE','education-schools','Schulen');
INSERT INTO Translations VALUES(NULL,'DE','education-schools-DESC','Seiten von Schulen und Universitäten.');
INSERT INTO Translations VALUES(NULL,'DE','alcohol','Alkohol');
INSERT INTO Translations VALUES(NULL,'DE','alcohol-DESC','Seiten von Brauereien, Keltereien und Brennereien. Ebenso werden in dieser Kategorie Seiten aufgenommen, die erklären, wie man Alkohol herstellt.');
INSERT INTO Translations VALUES(NULL,'DE','finance-moneylending','Finanzen/Geldverleih');
INSERT INTO Translations VALUES(NULL,'DE','finance-moneylending-DESC','Seiten, die sich speziell mit der Thematik Geldverleih und Kredite befassen, Kreditaufnahme und -abzahlung.');
INSERT INTO Translations VALUES(NULL,'DE','automobile-cars','Automobil/Autos');
INSERT INTO Translations VALUES(NULL,'DE','automobile-cars-DESC','Rund um das Auto: Hersteller, Zulieferer, Reparaturen u.ä.');
INSERT INTO Translations VALUES(NULL,'DE','sex-education','Sex/Sexualkunde.');
INSERT INTO Translations VALUES(NULL,'DE','sex-education-DESC','Seiten mit Erklärungen zur Sexualität und sexueller Gesundheit.');
INSERT INTO Translations VALUES(NULL,'DE','remotecontrol','Fernkontrolle');
INSERT INTO Translations VALUES(NULL,'DE','remotecontrol-DESC','Seiten mit Diensten, die es ermöglichen, an entfernten Rechnern zu arbeiten (auch aber nicht nur durch Firewall durch). Normales, traditionelle VPN Zugänge werden nicht betrachtet.');
INSERT INTO Translations VALUES(NULL,'DE','forum','Foren');
INSERT INTO Translations VALUES(NULL,'DE','forum-DESC','Forums- und Diskussionsseiten sowie teilweise auch Blogs. ');
INSERT INTO Translations VALUES(NULL,'DE','urlshortener','Kurz-URLs');
INSERT INTO Translations VALUES(NULL,'DE','urlshortener-DESC','Dom?nen, die das Erzeugen von Kurz-URLs aus normalen URLs erm?glichen. ');
INSERT INTO Translations VALUES(NULL,'DE','models','Models');
INSERT INTO Translations VALUES(NULL,'DE','models-DESC','Modelagenturen, Modelle und Supermodels. Beinhaltet Fanseiten ebenso, wie Bilder mit Models. Keine Pornographie.');
INSERT INTO Translations VALUES(NULL,'DE','ringtones','Klingeltöne');
INSERT INTO Translations VALUES(NULL,'DE','ringtones-DESC','Informationen zu und Laden von Klingeltönen.');
INSERT INTO Translations VALUES(NULL,'DE','redirector','Proxy');
INSERT INTO Translations VALUES(NULL,'DE','redirector-DESC','Seiten mit Proxydiensten, die eine aktive Umgehung des URL Filters erlauben.');
